server:
  port: 8090
  servlet:
    context-path: /api/v1/cardtest
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/cla_config?useSSL=false&allowPublicKeyRetrieval=TRUE&createDatabaseIfNotExist=true
    username: admin
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  ai:
    ollama:
      base-url: http://localhost:11434/
      chat:
        model: llama3
        options:
          keep-alive: 10m
          temperature: 1 
  web:
    resources:
      static-locations:
        - file:static-files
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

data:
  gen:
    service:
      baseUrl: http://localhost:8089
      
jenkins:
  job.name: CARDTEST.AI
  baseUrl: http://192.168.3.195:8080
  creds: admin:0d9722b0993b43b594727e3a7c73737b #sankha:1155b93dd2fba10d968714ad841c910c59 - sankha
  
host:
  ip: http://192.168.3.195:8090
  
github:
  api:
    repo:
      url: https://api.github.com/repos/sbandgar-verinite/automation-scripts/contents/src/test/resources/features
      branch: main
      auth.token: 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  #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 - sankha
  commit:
    name: Sumeet Bandgar
    email: sumeet.bandgar@verinite.com
    message:
    
camunda:
  host:
    ip: http://192.168.3.101:9093
  bpmn:
    process:
      id: runplan