server:
  port: 8090
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/cla_config?useSSL=false&allowPublicKeyRetrieval=TRUE&createDatabaseIfNotExist=true
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    ollama:
      base-url: http://localhost:11434/
      chat:
        model: llama3